[functions]
  verify_jwt = false

[[functions.routes]]
  path = "/dailyBonus"
  method = "GET"

[[functions.routes]]
  path = "/validateGame"
  method = "POST"

[[functions.routes]]
  path = "/handleCapture"
  method = "POST"